# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package to TestPyPi

on:
  release:
    types: [prereleased]
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        description: Release tag version
        default: true

permissions:
  contents: read

jobs:
  if_manually_run:
    if:  github.event.inputs.release == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get tag
      shell: bash
      run: |
        if tag=$(git describe --tags --abbrev=0 2>/dev/null);then
          echo "Found tag $tag"
          echo "TAG=$tag" >> $GITHUB_ENV
        else
          echo "No tag found, exiting"
          exit 1
        fi
  if_released:
    if: github.event.release.tag_name
    runs-on: ubuntu-latest
    steps:
    - name: Get tag
      shell: bash
      run: |
        tag=${{ github.event.release.tag_name }}
        echo "Found tag $tag"
        echo "TAG=$tag" >> $GITHUB_ENV
  release-build:
    strategy:
      fail-fast: false
      matrix:
        p-version: ["3.10","3.11","3.12","3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.p-version}}
      - name: Build release distributions
        shell: bash
        run: |
          sed -i "s/__VERSION__/$TAG/g" pyproject.toml
          # NOTE: put your own distribution build steps here.
          python -m pip install build
          python -m build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
  publish-to-testpypi:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: testpypi
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      # url: https://pypi.org/p/YOURPROJECT
      #
      # ALTERNATIVE: if your GitHub Release name is the PyPI project version string
      # ALTERNATIVE: exactly, uncomment the following line instead:https://test.pypi.org/manage/projects/
      url: https://test.pypi.org/project/project_visualization_tool_GDeLuisi/${{ github.event.prerelease.tag_name }}
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TESTPYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
